name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Cambia 'nombre-de-tu-carpeta' por el nombre real de la carpeta de tu proyecto
    defaults:
      run:
        working-directory: ./nombre-de-tu-carpeta

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Dar permisos a Gradle
        run: chmod +x ./gradlew

      - name: Compilar APK
        run: ./gradlew assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: Lag-city-APK
          path: nombre-de-tu-carpeta/app/build/outputs/apk/debug/*.apk
